name: Build and Deploy Marp Slides

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

          #- name: Install fonts (Noto Sans + Noto Sans Myanmar)
          #  run: |
          #    sudo apt-get update
          #    sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji fonts-noto-unhinted fonts-noto-core fonts-noto-mono fonts-noto-extra fonts-noto-ui-core fonts-noto-ui-extra

      - name: Install Myanmar Sanpya font
        run: |
          mkdir -p ~/.fonts
          cp fonts/MyanmarSanpya.ttf ~/.fonts/
          fc-cache -f -v

      - name: Export slides to HTML and PDF
        run: |
          mkdir dist
          marp SLIDES.md --html --output dist/index.html
          marp SLIDES.md --pdf --output dist/slides.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Get timestamp + optional Git tag
        id: version
        run: |
          DT=$(date -u +"%Y%m%d-%H%M%S")
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          VERSION="v${DT}"
          [ -n "$TAG" ] && VERSION="${VERSION}-${TAG}"
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          files: dist/slides.pdf
          draft: true             # ← Set `false` to publish immediately
          prerelease: false       # ← Set `true` if tagging nightly builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
